### ISSUE TITLE
cannot start SP slipstream version of AEM in demo-machine 

### ISSUE THREAD

**Issue by chrismade** [Adobe-Marketing-Cloud/aem-demo-machine#18]
When using an AEM.jar which has a SP included, built like described here:
http://blogs.adobe.com/experiencedelivers/experience-management/adding-packages-aem-jar-file/
by Feike Visser such jar files don't work in the demo machine - the demo machine is reporting "successfully started in xx seconds" but it is not successfully started.

curl is reporting "503 Service Unavailable"
Startup in progressMacintosh-2:~ chris$ curl -v http://127.0.0.1:4502
- Rebuilt URL to: http://127.0.0.1:4502/
-   Trying 127.0.0.1...
- Connected to 127.0.0.1 (127.0.0.1) port 4502 (#0)
  > GET / HTTP/1.1
  > Host: 127.0.0.1:4502
  > User-Agent: curl/7.43.0
  > Accept: _/_
  > 
  < HTTP/1.1 503 Service Unavailable
  < Date: Sat, 23 Jul 2016 11:47:24 GMT
  < Content-Type: text/plain; charset=UTF-8
  < Transfer-Encoding: chunked
  < Server: Jetty(9.2.9.v20150224)
  < X-Powered-By: Jetty(9.2.9.v20150224)
  < 
- Connection #0 to host 127.0.0.1 left intact

and crx-quickstart/logs/stderr.log
is showing:
23.07.2016 10:13:53.296 _ERROR_ [FelixStartLevel] ERROR: Error starting launchpad:resources/install/23/cq-compat-codeupgrade-1.5.6.jar (org.osgi.framework.BundleException: Unresolved constraint in bundle com.day.cq.cq-compat-codeupgrade [135]: Unable to resolve 135.0: missing requirement [135.0] osgi.wiring.package; (osgi.wiring.package=com.day.cq.commons.jcr))
org.osgi.framework.BundleException: Unresolved constraint in bundle com.day.cq.cq-compat-codeupgrade [135]: Unable to resolve 135.0: missing requirement [135.0] osgi.wiring.package; (osgi.wiring.package=com.day.cq.commons.jcr)
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4095)
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1368)
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
    at java.lang.Thread.run(Thread.java:745)
Opening browser using cmd=open http://localhost:4502/
Installation time:88 seconds

This AEM-jar file outside demo-machine is starting without any issues and installs SP on first call as expected. I haven't found any hint what is the best way to include (already downloaded) SP and hotfix files in the demo-machine so that they got applied when building a new demo - so I thought incorporating them into the AEM-jar might be a good idea - obviously it isn't

Maybe this is something which is easy to fix - if not, then please close this issue as WONTFIX

**Comment by coatpont** [comment]
I'm not familiar with this "custom AEM jar" process - however the demo machine does support the installation of service packs. in the /dist/bin folder, assuming your AEM jar file is something like aem62.jar, then just place the service pack file in the same folder with the -sp suffix (e.g. aem62-sp.zip) and if the demo.servicepack properties is set to true (it's the default value), then AEM will be installed with this service pack upfront (entire instance booting up with the service pack code). Can you review/test and close this issue if it works for you? (this method is the one tested by our QE organization)

**Comment by chrismade** [comment]
yes, I confirm it is working

for a JAR file like:
cq61-author-4502.jar
the corresponding Service Pack  has to be:
cq61-author-4502-sp.zip
both files in dist/bin folder
BTW: for the demo machine I'd rather rename cq61-author-4502.jar to cq61.jar as role and port will be set by properties later by script

and for hotfixes:
a directory dist/hotfixes/all
must be created - containing the files like
cq-6.1.0-hotfix-8651-1.2.zip
cq-6.1.0-hotfix-9113-1.0.zip
etc
"all" contains the hot fixes which belongs to core AEM - whereas there might be also hotfixes for packages (folder has then package name instead of 'all' )

Either I missed that reading the wiki - or it is not there (please copy/paste from here if this is the case)

case can be closed - thanks for support on weekends ;-)
