### ISSUE TITLE
Please install the Adobe-only properties before using this feature while Downloading snapshot

### ISSUE THREAD

**Issue by niravpatel97120** [Adobe-Marketing-Cloud/aem-demo-machine#21]
Running ANT target: download_snapshot
Sorry, this target couldn't be completed properly
The error message is:
Please install the Adobe-only properties before using this feature (Search for AEM Demo Machine in Adobe's Wiki for further instructions)

**Comment by coatpont** [comment]
As per the error message, please log into the Adobe Wiki, search for the AEM Demo Machine page and download the new internal properties, that will enable this download feature later (only available to users with access to the Adobe network).

**Comment by niravpatel97120** [comment]
Can you guide me visually?

**Comment by coatpont** [comment]
For this particular feature, I can only help you if you have access to the Adobe network as an employee or contractor, sorry!
