### ISSUE TITLE
demo machine can't detect running instance

### ISSUE THREAD

**Issue by oswjos** [Adobe-Marketing-Cloud/aem-demo-machine#30]
Hi guys,

After installing my first demo, it seems the demo machine is unaware that there is already an instance running. It displays this message and it gets stuck there:

Waiting for the Author instance to be started...

I can see the author instance already started and I am able to log in just fine. 

I suspect this is also the reason why I am able to download the latest hotfixes but I am not able to install them (I guess since the demo machine doesn't know there is an instance running it doesn't present the option to install the packages).

Also, I didn't see an option to support the Cumulative Fix Packs.

Finally when I click in "Search for Updates" on the UI, it tells me to do a git pull, but when I do a git pull, it says everything is already up to date.

Can you guys please help me?  I am using the demo machine on macOS Sierra Version 10.12.4, java version "1.8.0_121", AEM 6.1.

Thanks a bunch!

**Comment by coatpont** [comment]
hi there -

The demo machine allows to run multiple instances of AEM demo environments at once - however on different ports. The demo machine "start" sequence includes a test verifying that the requested port is available, so it's odd that you ended up in this situation - don't have a good theory at the moment.

Note that hotfixes are installed at "build" time - not later. (by being placed in the /demos/demo-name/author/crx-quickstart/install before the first startup).

For Cumulative Fix Packs and Service Packs, they can be installed automatically by having them named like this: assuming you are installing aem62.jar in /dist/bin, then put the CFP/FP in there with the -sp suffix: aem62-sp.zip. It will get installed automatically if demo.servicepack=true (which is the default value).

"Search for Updates" is a little broken at the moment - will investigate eventually - as long as you are current with Git, you're ok.
