### ISSUE TITLE
AEM Content Services Feature Flag

### ISSUE THREAD

**Issue by frazerATadobe** [Adobe-Marketing-Cloud/aem-demo-machine#34]
Would it make sense to add a config option for setting the "AEM Content Services Feature Flag" to "enabled"? Something like "demo.contentservices=true"?

![screen shot 2017-05-09 at 3 02 16 pm](https://cloud.githubusercontent.com/assets/17181888/25867758/944abb16-34c8-11e7-8a89-d51929a8461c.png)
![screen shot 2017-05-09 at 3 04 34 pm](https://cloud.githubusercontent.com/assets/17181888/25867844/db400d5a-34c8-11e7-8c04-7c639bf02dd6.png)

**Comment by coatpont** [comment]
I agree, I just pushed the change as a new feature.

**Comment by Rampai94** [comment]
I can't see the Content Services option in my Global Navigation. Is this a known issue? 

I have checked the ContentServicesFeatureFlag.
