### ISSUE TITLE
AEM Commarce demo is not created on Windows 2008 R2 server with external Mongo instance

### ISSUE THREAD

**Issue by kapilmalik84** [Adobe-Marketing-Cloud/aem-demo-machine#35]
Hi Team,
Building a new publish demo named testmongo
      Stopping and removing demo instance for testmongo
      Stopping all running demo instances
HMECD000113V
Sorry, this target couldn't be completed properly
The error message is:
The following error occurred while executing this line:
C:\aem-demo-machine\build.xml:245: The following error occurred while executing this line:
C:\aem-demo-machine\build.xml:1365: The following error occurred while executing this line:
C:\aem-demo-machine\build.xml:1415: Execute failed: java.io.IOException: Cannot run program "mongo": CreateProcess error=2, The system cannot find the file specified

I do have an external mongod running on my 2008 R2 server. I have changed the demo property 	"demo.mongo.external" as true. 
Demo machine says that "demo.mongo.external" "Allows to use an existing MongoDB server instead of the one managed by the Demo Machine" however if i create the directory "C:\aem-demo-machine\mongodb\bin" and put all the bin folder content from "C:\Program Files\MongoDB\Server\3.4\bin" and keep the "demo.mongo.external" value as false then also the machine can not start Mongod and create the demo.
Please suggest.
Kapil Malik

**Comment by coatpont** [comment]
please check https://github.com/Adobe-Marketing-Cloud/aem-demo-machine/wiki/Infrastructure on how to point at an external Mongo instance (by default, but that's for MacOS only, it's pointing at the mongoDB instance that can be setup with the demo machine itself)

**Comment by kapilmalik84** [comment]
Thanks Coatpont,
i need more help here to understand the values we need to provide on a windows 2008 R2 machine having an external mongobd install.
can you please suggest if the values are right?
Prpopery name              Default value                                     custom value
1. demo.mongo	mongodb-osx-x86_64-3.2.9	C:\Program Files\MongoDB\Server\3.4\bin\mongo.exe
2. demo.mongo.external	false	                                              true	
3. demo.mongo.path	mongo	                        C:\Program Files\MongoDB\Server\3.4\bin\mongo.exe
4. demo.mongo.service	 false		                          "What should be the value here in my case"

Thanks
Kapil

**Comment by coatpont** [comment]
I think all you need is 
demo.mongo.external=true
demo.mongo.service=false (this is used to start/stop it as a service on linux only).

**Comment by kapilmalik84** [comment]
Mongod should be running on the same system?
should i use <mongo-install>/bin/mongod --dbpath <mongo-dbpath> as the command to start mongo?
i was getting an IOException with error code=5
but after making the change to Mongo.exe and mongod.exe security settings to give "Full Control" i am not getting that exception now.

**Comment by coatpont** [comment]
No, Mongo doesn't need to be on the same host.
You'll have to start/stop MongoDb separately wit Mongo scripts

**Comment by coatpont** [comment]
on precision though, this configuration (external Mongo on Windows) has not be tested before (just one MacOS), so there might be side effects to investigate.

**Comment by kapilmalik84** [comment]
ok,
This is giving error while starting the AEM for the first time. This is from Error.log
15.05.2017 12:16:41.714 *ERROR* [FelixStartLevel] org.apache.jackrabbit.oak-core [org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreService(69)] Failed creating the component instance; see log for reason
15.05.2017 12:24:36.264 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.AbsoluteTimeoutHandlerProxyImpl.xml
15.05.2017 12:24:36.265 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQDynamicParticipantExecutor.xml
15.05.2017 12:24:36.266 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowExtProcessProxy.xml
15.05.2017 12:24:36.266 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.xml
15.05.2017 12:24:36.266 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.ScriptContextProviderImpl.xml
15.05.2017 12:24:36.266 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.impl.CQPayloadMap.xml
15.05.2017 12:24:36.461 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.AbsoluteTimeoutHandlerProxyImpl.xml
15.05.2017 12:24:36.461 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQDynamicParticipantExecutor.xml
15.05.2017 12:24:36.462 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowExtProcessProxy.xml
15.05.2017 12:24:36.462 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.xml
15.05.2017 12:24:36.462 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.ScriptContextProviderImpl.xml
15.05.2017 12:24:36.462 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.impl.CQPayloadMap.xml
15.05.2017 12:24:36.507 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.AbsoluteTimeoutHandlerProxyImpl.xml
15.05.2017 12:24:36.508 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQDynamicParticipantExecutor.xml
15.05.2017 12:24:36.508 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowExtProcessProxy.xml
15.05.2017 12:24:36.508 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.xml
15.05.2017 12:24:36.508 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.ScriptContextProviderImpl.xml
15.05.2017 12:24:36.509 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.impl.CQPayloadMap.xml
15.05.2017 12:24:36.551 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.AbsoluteTimeoutHandlerProxyImpl.xml
15.05.2017 12:24:36.551 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQDynamicParticipantExecutor.xml
15.05.2017 12:24:36.551 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowExtProcessProxy.xml
15.05.2017 12:24:36.551 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.xml
15.05.2017 12:24:36.552 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.ScriptContextProviderImpl.xml
15.05.2017 12:24:36.553 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.impl.CQPayloadMap.xml
15.05.2017 12:24:36.594 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.AbsoluteTimeoutHandlerProxyImpl.xml
15.05.2017 12:24:36.594 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQDynamicParticipantExecutor.xml
15.05.2017 12:24:36.595 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowExtProcessProxy.xml
15.05.2017 12:24:36.595 *ERROR* [qtp1625153106-163] org.apache.felix.metatype Missing element AD in element OCD : bundle://283.0:0/OSGI-INF/metatype/com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.xml

**Comment by coatpont** [comment]
Sorry I don't know where this is coming from, it has not been reported before

**Comment by coatpont** [comment]
sorry no more suggestion please re-open if still a problem
