### ISSUE TITLE
Would be great to indicate in the UI what packages are already downloaded

### ISSUE THREAD

**Issue by elafargue** [Adobe-Marketing-Cloud/aem-demo-machine#4]
... and whether there are updates available.

**Comment by coatpont** [comment]
thanks Edouard - adding to the backlog - not quite sure on how to do it yet :)

**Comment by coatpont** [comment]
@elafargue I just checked in a first version of a "check for updates" feature (one known issue so far, on Windows there's a false positive on the AEM demo machine itself, but not with the packages)
