### ISSUE TITLE
Getting error while downloading snapshot 

### ISSUE THREAD

**Issue by suryakant-patil** [Adobe-Marketing-Cloud/aem-demo-machine#41]
As per video reference downloading snapshot I am getting below error.
Please let me know how to configure correctly.
Please install the Adobe-only properties before using this feature (Search for the main AEM Demo Machine page in Adobe's corporate Wiki for detailed instructions and the attached set of properties). The following properties need new values: demo.download.aem.artifactory, demo.download and demo.scripts.

**Comment by coatpont** [comment]
if you have access to the Adobe network/VPN just use the "one click setup" button under New/Properties. If not, then you'll have to use a regular AEM .jar file under the /dist/bin folder, you won't be able to download the latest Adobe-only snapshot
