### ISSUE TITLE
mysql link for download does not work

### ISSUE THREAD

**Issue by cboris** [Adobe-Marketing-Cloud/aem-demo-machine#43]
**Download of mysql fails**
Running ANT target: download_mysql
      Downloading MySQL DB for MacOS
      Downloading http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.35-macos10.12-x86_64.tar.gz
BUILD SUCCESSFUL
Total time: 1 second
Running ANT target: install_mysql
      Installing MySQL database on MacOS
Sorry, this target couldn't be completed properly
The error message is:
Problem expanding gzip Not in GZIP format

**Comment by coatpont** [comment]
this is fixed
