### ISSUE TITLE
Sites  >  Download Demo Add-on, aem-demomachine-sites empty and sites addon gives error

### ISSUE THREAD

**Issue by FarhanMohammed** [Adobe-Marketing-Cloud/aem-demo-machine#5]
Hi,

I just got the AEM Demo Machine up and running, created a demo instance and it works on port 4502&4503. 
Add-ons > Assets Demo Addon was installed but Sites gives same error . 
When I try to download the AEM Sites Demo  Add on under Add-ons >  Sites  >  Download Demo Add-on.
I get this error:  

Running ANT target: download_sites
      Downloading Latest AEM Sites Demo Add-on in /dist/downloads
      Download in progress, please wait until build is successful
      Extracting Latest AEM Sites Demo Add-on in /dist/sites
Sorry, this target couldn't be completed properly
The error message is:
Error while expanding C:\Users\farhan.mohammed\aem-demo-machine\dist\downloads\aem-demomachine-sites.zip
java.util.zip.ZipException: archive is not a ZIP archive

**Comment by coatpont** [comment]
can you please try again, making sure you are using the latest version of the Demo Machine? This seems to work on my end.

**Comment by coatpont** [comment]
verified again today, works fine
